# ARRAY

In [ ]:
#  typecode     c type       pythontype       min size(bytes)
#    b        signed char      int              1
#    B       unsigned char     int              1
#    u        Py_UNICODE    unicode char        2
#    h       signed short      int              2
#    H       unsigned short    int              2
#    i         signed int      int              2
#    I       unsigned int      int              2
#    l        signed long      int              4 
#    L       unsigned long     int              4
#    f          float         float             4
#    d         double         float             4


In [2]:
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
print(a)

array('i', [3, 5, 7, 8, 2, 4, 1, 0])


In [3]:
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
print(a.buffer_info())
#first one is address and second one is value

(2045000713968, 8)


In [4]:
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
print(a.typecode)
#data type used

i


In [8]:
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
a.remove(8)
a.reverse()
a.append(10)
a.remove(3)
print(a)
#reverse the array

array('i', [0, 1, 4, 2, 7, 5, 10])


In [6]:
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
print(a[0])

3


In [14]:
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
for i in range(8):
    print(a[i],end=" ")
    

3 5 7 8 2 4 1 0 

In [17]:
#in character
import array as arr
a = arr.array('u',['r','e','i','d','b'])
for i in range(5):
    print(a[i],end=" ")

r e i d b 

In [19]:
#to copy array in new array with same data type
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
newA = arr.array(a.typecode,(j for j in a))
for i in range(8):
    print(newA[i],end=" ")

3 5 7 8 2 4 1 0 

In [20]:
#to copy array in new array with same data type with square with number
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
newA = arr.array(a.typecode,(j*j for j in a))
for i in range(8):
    print(newA[i],end=" ")

9 25 49 64 4 16 1 0 

In [21]:
# using while loop
import array as arr
a = arr.array('i',[3,5,7,8,2,4,1,0])
newA = arr.array(a.typecode,(j*j for j in a))
i=0
while i<len(newA):
    print(newA[i],end=" ")
    i=i+1

9 25 49 64 4 16 1 0 

In [3]:
#user input and insert value in array
import array as arr
a = arr.array('i',[])
n = int(input("enter the length of the array : "))
for i in range(n):
    x = int(input("enter the value : "))
    a.append(x)
print(a,end=" ")

enter the length of the array : 4
enter the value : 8
enter the value : 3
enter the value : 6
enter the value : 1
array('i', [8, 3, 6, 1]) 

In [5]:
#searching of the element in array linear search
import array as arr
a = arr.array('i',[])
n = int(input("enter the length of the array : "))
for i in range(n):
    x = int(input("enter the value : "))
    a.append(x)
print(a,end=" ")
print("\n")

y = int(input("enter the value to be searched : "))
for i in range(n):
    if(y==a[i]):
        print(y," value found")
        break
else:
    print("not found")

enter the length of the array : 6
enter the value : 45
enter the value : 89
enter the value : 91
enter the value : 52
enter the value : 63
enter the value : 37
array('i', [45, 89, 91, 52, 63, 37]) 

enter the value to be searched : 63
63  value found


# Array using Numpy

In [6]:
# using numpy  array
import numpy as np
a = np.array([1,6,4,7,9,8,3])
print(a)

[1 6 4 7 9 8 3]


In [7]:
import numpy as np
a = np.array([1,6,4,7,9,8,3])
print(a.dtype)

int32


In [11]:
import numpy as np
a = np.array([1,6.4,4,7.9,9,8,3])
print(a.dtype)
print(a)
#every value converted into float

float64
[1.  6.4 4.  7.9 9.  8.  3. ]


In [16]:
# using numpy linspace
import numpy as np
a = np.linspace(0,10)
print(a.dtype)
print(a)
#linspace take three input 1. start 2. stop  3.third one is break the digit
#in that number different parts

float64
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [17]:
# using numpy arange()
import numpy as np
a = np.arange(0,10)
print(a.dtype)
print(a)
#linspace take three input 1. start 2. stop  3.third one is step

int32
[0 1 2 3 4 5 6 7 8 9]


In [19]:
# using numpy logspacee()
import numpy as np
a = np.logspace(0,50,5)
print(a.dtype)
print(a)
print('%.2f' %a[0])
print('%.2f' %a[4])
#linspace take three input 1. start 2. stop  3.third one is break range in 5 parts into log format

float64
[1.00000000e+00 3.16227766e+12 1.00000000e+25 3.16227766e+37
 1.00000000e+50]
1.00
100000000000000007629769841091887003294964970946560.00


In [23]:
# using numpy zeros()
import numpy as np
a = np.zeros(5,dtype='int')
print(a.dtype)
print(a)

int32
[0 0 0 0 0]


In [25]:
# using numpy ones()
import numpy as np
a = np.ones(10,dtype='int')
print(a.dtype)
print(a)

int32
[1 1 1 1 1 1 1 1 1 1]


In [32]:
import numpy as np
import array as arr
a=arr.array('i',[])
n = int(input("length of array : "))
for i in range(n):
    x = int(input("value : "))
    a.append(x)
print(a,end=" ")
print("\n")
for i in range(n):
    a[i]=a[i]+5
print(a,end=" ")

length of array : 6
value : 56
value : 89
value : 23
value : 49
value : 93
value : 37
array('i', [56, 89, 23, 49, 93, 37]) 

array('i', [61, 94, 28, 54, 98, 42]) 

In [33]:
import numpy as np
a = np.array([1,6,4,7,9,8,3])
a= a+5
print(a)


[ 6 11  9 12 14 13  8]


In [34]:
import numpy as np
a = np.array([16,66,40,79,94,86,13])
b =  np.array([51,62,49,74,93,18,31])
c= a+b
print(c)

[ 67 128  89 153 187 104  44]
